// Code generated by MockGen. DO NOT EDIT.
// Source: ./common/client/rancher/client.go

// Package mock_rancher is a generated GoMock package.
package sdkmocks

import (
	ipapisdk "github.com/phoenixnap/go-sdk-bmc/ipapi"
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIpSdkClient is a mock of IpSdkClient interface.
type MockIpSdkClient struct {
	ctrl     *gomock.Controller
	recorder *MockIpSdkClientMockRecorder
}

// MockIpSdkClientMockRecorder is the mock recorder for MockIpSdkClient.
type MockIpSdkClientMockRecorder struct {
	mock *MockIpSdkClient
}

// NewMockIpSdkClient creates a new mock instance.
func NewMockIpSdkClient(ctrl *gomock.Controller) *MockIpSdkClient {
	mock := &MockIpSdkClient{ctrl: ctrl}
	mock.recorder = &MockIpSdkClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIpSdkClient) EXPECT() *MockIpSdkClientMockRecorder {
	return m.recorder
}

// IpBlockPost mocks base method.
func (m *MockIpSdkClient) IpBlockPost(ipBlockCreate ipapisdk.IpBlockCreate) (ipapisdk.IpBlock, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IpBlockPost", ipBlockCreate)
	ret0, _ := ret[0].(ipapisdk.IpBlock)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// IpBlockPost indicates an expected call of ClusterPost.
func (mr *MockIpSdkClientMockRecorder) IpBlockPost(ipBlockCreate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IpBlockPost", reflect.TypeOf((*MockIpSdkClient)(nil).IpBlockPost), ipBlockCreate)
}

// IpBlocksGet mocks base method.
func (m *MockIpSdkClient) IpBlocksGet() ([]ipapisdk.IpBlock, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IpBlocksGet")
	ret0, _ := ret[0].([]ipapisdk.IpBlock)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// IpBlocksGet indicates an expected call of ClustersGet.
func (mr *MockIpSdkClientMockRecorder) IpBlocksGet() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IpBlocksGet", reflect.TypeOf((*MockIpSdkClient)(nil).IpBlocksGet))
}

// IpBlocksGetById mocks base method.
func (m *MockIpSdkClient) IpBlocksGetById(ipBlockId string) (ipapisdk.IpBlock, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IpBlocksGetById", ipBlockId)
	ret0, _ := ret[0].(ipapisdk.IpBlock)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// IpBlocksGetById indicates an expected call of ClusterGetById.
func (mr *MockIpSdkClientMockRecorder) IpBlocksGetById(ipBlockId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IpBlocksGetById", reflect.TypeOf((*MockIpSdkClient)(nil).IpBlocksGetById), ipBlockId)
}

// IpBlocksIpBlockIdDelete mocks base method.
func (m *MockIpSdkClient) IpBlocksIpBlockIdDelete(ipBlockId string) (ipapisdk.DeleteIpBlockResult, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IpBlocksIpBlockIdDelete", ipBlockId)
	ret0, _ := ret[0].(ipapisdk.DeleteIpBlockResult)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// IpBlocksIpBlockIdDelete indicates an expected call of ClusterDelete.
func (mr *MockIpSdkClientMockRecorder) IpBlocksIpBlockIdDelete(ipBlockId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IpBlocksIpBlockIdDelete", reflect.TypeOf((*MockIpSdkClient)(nil).IpBlocksIpBlockIdDelete), ipBlockId)
}
